# Generated by Skyramp v1.3.29 on 2026-06-25 19:03:21.024150759 +0000 UTC m=+254.796720316
# Command: skyramp generate contract rest http://localhost:8094/api/v1/monitor/messages/summary \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_messages_summary_unauth_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8094")

# contract test for /api/v1/monitor/messages/summary GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # No auth header — testing unauthenticated access
    headers = {}

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/monitor/messages/summary",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 403
    assert skyramp.get_response_value(summary_GET_response, "detail") == "No authentication credentials provided"


if __name__ == "__main__":
    test_summary_get()
