# Generated by Skyramp v1.3.29 on 2026-06-25 19:03:18.059971827 +0000 UTC m=+251.832541384
# Command: skyramp generate contract rest http://localhost:8094/api/v1/monitor/messages/summary \
# 		--api-schema http://localhost:8094/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_messages_summary_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8094")

# contract test for /api/v1/monitor/messages/summary GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_summary_GET_response_body = r'''{
        "flows_with_messages": 0,
        "total_messages": 0,
        "total_sessions": 0
    }'''

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/v1/monitor/messages/summary",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.check_schema(summary_GET_response, expected_summary_GET_response_body)
    assert skyramp.get_response_value(summary_GET_response, "flows_with_messages") is not None
    assert skyramp.get_response_value(summary_GET_response, "total_messages") is not None
    assert skyramp.get_response_value(summary_GET_response, "total_sessions") is not None
    assert skyramp.get_response_value(summary_GET_response, "total_messages") >= 0
    assert skyramp.get_response_value(summary_GET_response, "total_sessions") >= 0
    assert skyramp.get_response_value(summary_GET_response, "flows_with_messages") >= 0


if __name__ == "__main__":
    test_summary_get()
