# Generated by Skyramp v1.3.29 on 2026-06-25 19:13:22.887176648 +0000 UTC m=+238.922189435
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output flow_has_data_true_integration_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/langflow/langflow/tests/skyramp/scenario_flow-has-data-true.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8094")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "data": {
            "edges": [],
            "nodes": [
                {
                    "data": {
                        "id": "node1",
                        "node": {},
                        "type": "CustomComponent"
                    },
                    "id": "node1",
                    "position": {
                        "x": 0,
                        "y": 0
                    },
                    "type": "genericNode"
                }
            ]
        },
        "description": "Flow with nodes for testing has_data field",
        "name": "TestFlowWithNodes-1750876800"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "TestFlowWithNodes-1750876800"
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "Flow with nodes for testing has_data field"
    assert skyramp.get_response_value(endpoint_1_POST_response, "has_data") == True
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    flows = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    flows_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/flows/{flows}",
        method="GET",
        headers=headers,
        path_params={"flows": flows}
    )
    # Generated Assertions
    assert flows_GET_response.status_code == 200
    assert skyramp.get_response_value(flows_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(flows_GET_response, "name") == "TestFlowWithNodes-1750876800"
    assert skyramp.get_response_value(flows_GET_response, "has_data") == True
    assert skyramp.get_response_value(flows_GET_response, "description") == "Flow with nodes for testing has_data field"


if __name__ == "__main__":
    test_integration()
