# Generated by Skyramp v1.3.29 on 2026-06-25 19:03:34.145688689 +0000 UTC m=+267.918258237
# Command: skyramp generate integration rest \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--output flow_messages_summary_baseline_integration_test.py \
# 		--output-dir /home/runner/work/langflow/langflow/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/langflow/langflow/tests/skyramp/scenario_flow_messages_summary_baseline.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8094")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "data": {
            "edges": [],
            "nodes": []
        },
        "name": "summary-baseline-flow"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/flows/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "summary-baseline-flow"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/monitor/messages/summary",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert summary_GET_response.status_code == 200
    assert skyramp.get_response_value(summary_GET_response, "total_messages") >= 0
    assert skyramp.get_response_value(summary_GET_response, "total_sessions") >= 0
    assert skyramp.get_response_value(summary_GET_response, "flows_with_messages") >= 0


if __name__ == "__main__":
    test_integration()
