# Generated by Skyramp v1.3.29 on 2026-06-25 19:13:13.423022258 +0000 UTC m=+229.458035045
# Command: skyramp generate contract rest http://localhost:8094/api/v1/flows/ \
# 		--api-schema http://localhost:8094/openapi.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/langflow/langflow/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"ContractTestFlow-1750876800","data":{"nodes":[{"id":"node1","type":"genericNode","position":{"x":0,"y":0},"data":{"id":"node1"}}],"edges":[]}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8094")

# contract test for /api/v1/flows/ POST
def test_flows_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flows_POST_request_body = r'''{
        "data": {
            "edges": [],
            "nodes": [
                {
                    "data": {
                        "id": "node1"
                    },
                    "id": "node1",
                    "position": {
                        "x": 0,
                        "y": 0
                    },
                    "type": "genericNode"
                }
            ]
        },
        "name": "ContractTestFlow-1750876800"
    }'''

    # Expected Response Body
    expected_flows_POST_response_body = r'''{
        "name": "ContractTestFlow-1750876800",
        "has_data": true
    }'''

    # Execute Request
    flows_POST_response = client.send_request(
        url=URL,
        path="/api/v1/flows/",
        method="POST",
        body=flows_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flows_POST_response.status_code == 201
    assert skyramp.check_schema(flows_POST_response, expected_flows_POST_response_body)
    assert skyramp.get_response_value(flows_POST_response, "folder_id") is not None
    assert skyramp.get_response_value(flows_POST_response, "id") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") is not None
    assert skyramp.get_response_value(flows_POST_response, "name") == "ContractTestFlow-1750876800"
    assert skyramp.get_response_value(flows_POST_response, "has_data") == True


if __name__ == "__main__":
    test_flows_post()
